### ISSUE TITLE
Resume Title incorrect spacing in IE11

### ISSUE THREAD

**Issue by ghost** [jglovier/resume-template#13]
`<h2 class="header-title">{{ site.resume_title }}</h2>` doesn't display properly in IE11. See http://resume-template.joelglovier.com/ in IE 11

**Comment by jglovier** [comment]
Ugh...gross. For reference, here's a screenshot:

![image](https://cloud.githubusercontent.com/assets/1319791/22527214/4d1abf7a-e89c-11e6-9dde-76dbf0f2a0fa.png)

I'm tempted to just label as `wontfix` because I'm not supporting IE with this project, but this is probably important to address for cases where the title is longer than expected anyway.

Thanks for reporting. 🙇

**Comment by viper25** [comment]
Yes agree, IE ins't that important. Just reporting as an FYI only.

**Comment by grace-snow** [comment]
@jglovier I think you can close off this issue? I can't replicate in emulation mode on older versions of IE. 

From IE 8 and older the whole layout breaks a bit anyway, but I wouldn't put any effort into supporting such old browsers now (especially when Microsoft stopped supporting them a while ago!)

**Comment by jglovier** [comment]
>From IE 8 and older the whole layout breaks a bit anyway, but I wouldn't put any effort into supporting such old browsers now (especially when Microsoft stopped supporting them a while ago!)

@grace-snow good call. 👍 Thanks for the bump on this one!! 🙇
