### ISSUE TITLE
Forking and running results in 404 on main.css

### ISSUE THREAD

**Issue by philoushka** [jglovier/resume-template#2]
The `main.css` reference in `index.html` is 404.

I forked, changed personal details in `_config.yml`, and checked the look at
https://philoushka.github.io/resume-template

What did I do wrong, and how can I solve this problem?

I'm only reporting here as an issue to help smooth the process for other forkers.

**Comment by jglovier** [comment]
Hah - good catch. This is because the css link path in the head is written with the intent of a site-root relative URL. Will push a fix to accommodate hosting the project as a subdirectory in a moment.

You'll simply want to remove the first slash in `head.html` in the href value on line 15 in your fork.

**Comment by philoushka** [comment]
Thanks @jglovier !

![](http://www.reactiongifs.com/wp-content/uploads/2013/06/happy-prancing.gif)

**Comment by jglovier** [comment]
Closed via https://github.com/jglovier/resume-template/commit/099a503210f73851ee2d9aa234c888f1ee973885
