### ISSUE TITLE
Add icon for blog

### ISSUE THREAD

**Issue by mjclemente** [jglovier/resume-template#65]
Thanks so much for this template; it's fantastic.

Right now, while there's an icon for "website", there's not one specifically for "blog". In some cases these might be the same, but not always - or, someone might prefer to specifically indicate that it's their blog. The classic RSS broadcast icon might be a good fit for this. 

For what it's worth, I tried my hand at creating one, but it was my first attempt to use Illustrator, and I failed pretty hard.

Again, thanks for the template; if you have the time and think it makes sense, adding an icon for blog would be appreciated.

**Comment by jglovier** [comment]
@mjclemente thanks for opening this issue! I can def see the use case for linking to both blog and website, but the vast majority of the time most folks keep their blog writing on their website so I'm not inclined to add one here simply because of the principle that "everything added dilutes everything else".

>The classic RSS broadcast icon might be a good fit for this.

Just to address this point specifically, an RSS icon would be confusing to viewers as it would likely create the expectation of an RSS feed for the resume template itself.

I'm going to pass on this for now, but thanks for the suggestion! ❤️

**Comment by mjclemente** [comment]
Thanks for considering. 👍
